import {
  ALLOWED_MIME_TYPES_BY_KIND,
  MEDIA_MAX_BYTES_BY_KIND,
} from "@/lib/storage/upload-media";
import type { AccountRole } from "@/lib/auth/roles";
import type { MediaKind } from "./r2-client";

export type MediaVisibility = "public" | "private";

/**
 * Closed set of upload purposes — never a raw client-supplied
 * public/private flag. The server maps each purpose to a `visibility`
 * here, in one place, so a crafted or buggy request can never smuggle
 * a private chat attachment into public visibility, or vice versa.
 * Extend this map, not the caller, when a new upload flow is added.
 *
 * `visibility` is bookkeeping only now — every object lands in the
 * same private R2 bucket (`wacrm-media`) regardless. A `public` row is
 * reachable, without a session, through GET /api/media/public/[...key]
 * (which reads `visibility` from this same table, never from a
 * request parameter); a `private` row is only ever reachable through
 * the session-authed, account-scoped POST /api/media/resolve. See
 * r2-client.ts's doc comment for why there's no separate public
 * bucket/Custom Domain.
 */
export const MEDIA_PURPOSES = ["chat-attachment", "template-header"] as const;
export type MediaPurpose = (typeof MEDIA_PURPOSES)[number];

interface PurposeRule {
  visibility: MediaVisibility;
  /** Kinds this purpose accepts. */
  allowedKinds: readonly MediaKind[];
  /** Minimum role allowed to use this purpose — mirrors the role each
   *  flow's own existing route already requires (e.g. template submit
   *  is 'admin'-gated in /api/whatsapp/templates/submit), so uploading
   *  the media a flow needs can never be less restricted than actually
   *  using it. */
  minRole: AccountRole;
}

const PURPOSE_RULES: Record<MediaPurpose, PurposeRule> = {
  // message-composer.tsx / pending-audio-sync.ts — conversation-scoped
  // attachments. May contain anything from a property photo to a
  // lead's personal document; always private. 'agent' matches the role
  // /api/whatsapp/send itself requires.
  "chat-attachment": {
    visibility: "private",
    allowedKinds: ["image", "video", "audio", "document"],
    minRole: "agent",
  },
  // template-manager.tsx — WhatsApp template header image. Deliberately
  // reusable across every send of that template, to any number of
  // contacts; never carries a specific lead's personal data. Meta's own
  // header-image requirement (image only, JPEG/PNG) is enforced again
  // at MIME-check time below, not just here. 'admin' matches the role
  // /api/whatsapp/templates/submit itself requires.
  "template-header": {
    visibility: "public",
    allowedKinds: ["image"],
    minRole: "admin",
  },
};

/**
 * The permanent, directly-fetchable URL stored in `media_objects
 * .public_url` (and from there into e.g. `header_media_url`) for a
 * `visibility='public'` object — a route on the WACRM app's own
 * domain, not an R2 Custom Domain (see r2-client.ts's doc comment for
 * why). Starts with `https://`, so the existing compatibility rule
 * (`https://` = already fetchable, use as-is) covers it everywhere
 * with zero extra code — except `resolveMediaUrlForSend`, which
 * special-cases this exact shape to resolve it in-process instead of
 * making an HTTP round trip to our own server (see that module).
 */
export function buildPublicMediaUrl(key: string): string {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  if (!siteUrl) {
    throw new Error("NEXT_PUBLIC_SITE_URL is not configured — required to build a public media URL");
  }
  return `${siteUrl.replace(/\/+$/, "")}/api/media/public/${key}`;
}

/** Prefix every public media URL starts with — the exact string
 *  `buildPublicMediaUrl` produces before the key. Exported so
 *  `resolveMediaUrlForSend` can strip it without duplicating the
 *  `NEXT_PUBLIC_SITE_URL` + path-join logic. */
export function publicMediaUrlPrefix(): string {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  if (!siteUrl) {
    throw new Error("NEXT_PUBLIC_SITE_URL is not configured — required to resolve a public media URL");
  }
  return `${siteUrl.replace(/\/+$/, "")}/api/media/public/`;
}

export function isMediaPurpose(value: unknown): value is MediaPurpose {
  return typeof value === "string" && (MEDIA_PURPOSES as readonly string[]).includes(value);
}

export function ruleForPurpose(purpose: MediaPurpose): PurposeRule {
  return PURPOSE_RULES[purpose];
}

/**
 * Audio has no entry in `ALLOWED_MIME_TYPES_BY_KIND` (upload-media.ts)
 * because the composer's file *picker* never offers audio — voice
 * notes are always self-generated by the in-browser Opus recorder as
 * `audio/ogg` (see message-composer.tsx's finalizeRecording). Kept
 * separate here rather than added to that shared table so a picker-
 * facing MIME allowlist (used for `<input accept>` too) doesn't grow a
 * kind that has no picker.
 */
const AUDIO_MIME_TYPES = ["audio/ogg"] as const;

export function allowedMimeTypesForKind(kind: MediaKind): readonly string[] {
  if (kind === "audio") return AUDIO_MIME_TYPES;
  return ALLOWED_MIME_TYPES_BY_KIND[kind];
}

export interface MediaValidationError {
  error: string;
}

/**
 * Authoritative size/MIME check for one media kind — the same limits
 * the browser already checks client-side (MEDIA_MAX_BYTES_BY_KIND /
 * allowedMimeTypesForKind), re-checked here because a browser check is
 * only a UX nicety, never a security boundary. Used both against the
 * caller-declared size/type (presign-upload) and against R2's own
 * HeadObjectCommand result — the value that actually matters
 * (confirm-upload).
 */
export function validateSizeAndMime(
  kind: MediaKind,
  contentType: string,
  sizeBytes: number,
): MediaValidationError | null {
  const maxBytes = MEDIA_MAX_BYTES_BY_KIND[kind];
  if (sizeBytes > maxBytes) {
    return {
      error: `File too large for kind "${kind}": ${sizeBytes} bytes exceeds the ${maxBytes}-byte limit`,
    };
  }
  const allowedMimes = allowedMimeTypesForKind(kind);
  if (!allowedMimes.includes(contentType)) {
    return { error: `Unsupported content type "${contentType}" for kind "${kind}"` };
  }
  return null;
}

/**
 * Full request-time validation for presign-upload: kind must be valid
 * for the declared purpose, plus the size/MIME check above.
 */
export function validateMediaShape(
  purpose: MediaPurpose,
  kind: MediaKind,
  contentType: string,
  sizeBytes: number,
): MediaValidationError | null {
  const rule = ruleForPurpose(purpose);
  if (!rule.allowedKinds.includes(kind)) {
    return { error: `"${kind}" is not a valid media kind for purpose "${purpose}"` };
  }
  return validateSizeAndMime(kind, contentType, sizeBytes);
}
