import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";
import type { ResponderColor } from "@/lib/responder-color";
import type { CtwaReferral } from "@/lib/whatsapp/ctwa-referral";

export type { CtwaReferral } from "@/lib/whatsapp/ctwa-referral";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** "Já comprou comigo?" (migration 048). Defaults to false in the DB
   *  for every existing and new contact; changed only by explicit user
   *  action. Optional here because most queries don't select it. */
  has_purchased?: boolean;
  /** Reserved for a future AI suggestion (migration 048) — not read or
   *  written by any UI yet. */
  suggested_has_purchased?: boolean | null;
  /** "WhatsApp pessoal" (migration 082) — true once this lead moved off
   *  the business number (8810/profissional) onto the agent's personal
   *  WhatsApp. Defaults to false for every existing and new contact. */
  is_personal_whatsapp?: boolean;
  /** Lead-warmth score (migration 082), 0–10, written by the lead
   *  analysis job (src/lib/ai/lead-analysis.ts) alongside tags — never
   *  hand-edited. Defaults to 0. */
  ai_score?: number;
  /** Short, evidence-based explanation for the current `ai_score`. */
  ai_score_reason?: string | null;
  ai_score_updated_at?: string | null;
  /** "Hidden from the active Contacts list" (migration 069), same
   *  reversible-timestamp convention as deals.archived_at. */
  archived_at?: string | null;
  /** "Bloqueado" (migration 083) — same reversible-timestamp convention
   *  as archived_at, but distinct: a blocked contact stays visible in
   *  Contatos, just excluded from the Inbox, and the webhook
   *  (processMessage in src/app/api/whatsapp/webhook/route.ts) stops
   *  all processing for new inbound messages from them (no
   *  conversation/message insert, no automations, no AI, no
   *  follow-ups). */
  blocked_at?: string | null;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export interface Tag {
  id: string;
  /** Nullable since migration 050 — null for tags the lead-analysis AI
   *  creates, which have no human author. */
  user_id: string | null;
  name: string;
  color: string;
  category?: string | null;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

/** A saved tag combination (migration 040) — the raw `segments` row.
 *  Its tags live in the `segment_tags` join table; see
 *  `SegmentSummary` for the read model that carries `tag_ids`. */
export interface Segment {
  id: string;
  account_id: string;
  user_id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

/** Read model returned by the `list_segments_with_counts` RPC — a
 *  segment plus the tag ids it's built from and how many contacts
 *  currently match (AND semantics: every tag in `tag_ids`). */
export interface SegmentSummary {
  id: string;
  name: string;
  tag_ids: string[];
  contact_count: number;
  created_at: string;
}

export type AppointmentType =
  | 'call'
  | 'visit'
  | 'meeting'
  | 'proposal'
  | 'follow_up'
  | 'other';

export type AppointmentStatus = 'scheduled' | 'completed' | 'cancelled';

/** Real estate listing an appointment can reference (migration 045).
 *  Deliberately minimal — just enough to name/select a property from
 *  the appointment form; not a full listings module. */
export interface Property {
  id: string;
  account_id: string;
  user_id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

/** An empreendimento template for the Calculadora de Fluxo module
 *  (migration 064). `components` stores the reusable SHAPE of the
 *  payment flow (see src/lib/calculator/types.ts for its shape) — no
 *  per-unit amounts, those live only in the browser during a
 *  simulation. Isolated from the rest of the CRM's domain model on
 *  purpose; only this row shape is shared here. */
export interface CalcProject {
  id: string;
  account_id: string;
  user_id: string;
  name: string;
  components: unknown;
  created_at: string;
  updated_at: string;
}

/** Not yet acted on — columns exist (migration 045) so a future sync
 *  service can persist state without another migration, but nothing
 *  in the app writes anything other than 'not_synced' today. See
 *  src/lib/calendar/ for the (unimplemented) provider scaffolding. */
export type AppointmentSyncStatus = 'not_synced' | 'synced' | 'error';

/** A scheduled item on the Agenda (migration 041, extended 045).
 *  `scheduled_date` is YYYY-MM-DD, `scheduled_time` is HH:MM:SS or
 *  null for an all-day/unscheduled-time item. */
export interface Appointment {
  id: string;
  account_id: string;
  user_id: string;
  contact_id: string | null;
  /** Free-typed client name (migration 056) — set whenever a client is
   *  entered, whether or not it resolved to `contact_id`. Lets an
   *  appointment record who it's with without requiring the client to
   *  already exist as a `contacts` row. */
  client_name: string | null;
  property_id: string | null;
  title: string;
  description: string | null;
  /** Free-text notes, distinct from `description` — e.g. "cliente
   *  pediu para confirmar por telefone antes". */
  notes: string | null;
  type: AppointmentType;
  scheduled_date: string;
  scheduled_time: string | null;
  /** End of the appointment window, same day as scheduled_time (HH:MM:SS
   *  or null — migration 046). Not shown on the weekly agenda card, only
   *  in the detail view and in the Google Calendar event mapping. */
  scheduled_end_time: string | null;
  status: AppointmentStatus;
  /** Google Calendar sync placeholders (migration 045) — unused
   *  until src/lib/calendar/'s GoogleCalendarProvider is actually
   *  implemented. */
  external_calendar_id: string | null;
  sync_status: AppointmentSyncStatus;
  last_synced_at: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contacts(name, phone)`. */
  contact?: Pick<Contact, 'id' | 'name' | 'phone'> | null;
  /** Hydrated by queries that embed `properties(name)`. */
  property?: Pick<Property, 'id' | 'name'> | null;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  /** Manual "pin to top" flag (migration 060) — swipe-right on mobile /
   *  right-click context menu on desktop, in the conversation list. */
  pinned: boolean;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
  /**
   * Click-to-WhatsApp Ad origin (migration 055), captured from the first
   * inbound message's `referral` object and never overwritten afterward —
   * see `captureCtwaReferral` in the webhook route. Null when the lead
   * did not arrive via a CTWA ad. Shape is Meta's, all fields optional.
   */
  ctwa_referral?: CtwaReferral | null;
  /**
   * CTWA Free Entry Point 72h clock (migration 059) — independent of
   * the 24h service window. `ctwa_fep_started_at`/`ctwa_fep_active`
   * are a historical record ("was the benefit ever granted"), set once
   * by `maybeActivateCtwaFep` and never updated afterward. Whether the
   * benefit is *currently* live is derived from `ctwa_fep_expires_at`
   * vs. now — see `getCtwaFepStatus` in `src/lib/whatsapp/ctwa-fep.ts`.
   */
  ctwa_fep_started_at?: string | null;
  ctwa_fep_expires_at?: string | null;
  ctwa_fep_active?: boolean;
  /**
   * Outcome of the ~23h CTWA rescue nudge (migration 059) — see
   * `src/lib/whatsapp/ctwa-rescue.ts`. NULL = still a candidate / not
   * yet evaluated; otherwise terminal (evaluated at most once).
   */
  ctwa_rescue_status?: 'sent' | 'cancelled' | 'failed' | null;
  ctwa_rescue_sent_at?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType = 'conversation_assigned';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

// ============================================================
// AI suggestions (migration 049) — Central de IA
// ============================================================

export type AiSuggestionCategory =
  | 'pipeline_move'
  | 'action'
  | 'followup'
  | 'learning'
  | 'inconsistency'
  | 'other';

export type AiSuggestionStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'ignored'
  | 'done';

export interface AiSuggestion {
  id: string;
  account_id: string;
  contact_id?: string;
  conversation_id?: string;
  category: AiSuggestionCategory;
  title: string;
  description?: string;
  /** Category-specific detail — interpreted by `category`, not typed here. */
  payload?: Record<string, unknown>;
  status: AiSuggestionStatus;
  created_by?: string;
  resolved_by?: string;
  resolved_at?: string;
  /** "Adiar" (BLOCO 3/4) — a pending suggestion snoozed until this
   *  timestamp is hidden from the default pending view and resurfaces
   *  on its own once it passes. Null/undefined = not snoozed. */
  snoozed_until?: string | null;
  created_at: string;
  updated_at: string;
  /** Joined in by the list endpoint when contact_id is set. */
  contact?: { id: string; name: string; avatar_url?: string } | null;
}

// ============================================================
// Central de Ações (migration 066)
// ============================================================

export type ActionItemType = 'interest' | 'followup';
export type ActionItemStatus = 'pending' | 'completed' | 'cancelled';
export type ActionItemEventType =
  | 'created'
  | 'completed'
  | 'rescheduled'
  | 'context_changed'
  | 'outcome_recorded'
  | 'cancelled';

export interface ActionItem {
  id: string;
  account_id: string;
  contact_id: string;
  deal_id?: string | null;
  conversation_id?: string | null;
  type: ActionItemType;
  /** Interesse: "ação necessária". Follow-up: "motivo/contexto". */
  title: string;
  /** Optional context/observação for both types. */
  description?: string | null;
  /** Required (enforced by DB constraint) when type === 'followup'. */
  due_date?: string | null;
  /** Required alongside due_date (enforced by DB constraint) when
   *  type === 'followup' — migration 068. "HH:mm:ss" (Postgres `time`). */
  due_time?: string | null;
  status: ActionItemStatus;
  source_suggestion_id?: string | null;
  created_by?: string | null;
  resolved_by?: string | null;
  resolved_at?: string | null;
  /** Set atomically when a Follow-up message send is claimed (migration
   *  072) — the guard against sending the same Follow-up twice, from
   *  either the Pipeline or Central de Ações entry point. Cleared by
   *  {@link rescheduleFollowup} so a new cycle can send again. */
  followup_sent_at?: string | null;
  created_at: string;
  updated_at: string;
  /** Joined in by list queries. */
  contact?: Contact | null;
  deal?: Deal | null;
}

export interface ActionItemEvent {
  id: string;
  action_item_id: string;
  account_id: string;
  type: ActionItemEventType;
  payload?: Record<string, unknown>;
  created_by?: string | null;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
  /**
   * WhatsApp-style PDF preview fields — only ever populated for
   * `content_type === 'document'` messages whose file is a PDF, and
   * only once the best-effort server-side generation (inbound webhook
   * or outbound send) has completed. Migration 074. All three land
   * together; a message with a thumbnail always has the other two.
   */
  document_page_count?: number | null;
  document_file_size?: number | null;
  document_thumbnail_url?: string | null;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
  /** Joined via `pipeline:pipelines(name)` — the Campaigns audience picker labels stages by pipeline. */
  pipeline?: { name: string };
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  account_id: string;
  pipeline_id: string;
  stage_id: string;
  /** Order within its stage column (migration 063) — lower sorts first. */
  position: number;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  /** Migration 067 — set when the lead was removed from the active
   *  Pipeline board ("Arquivar"). Null/undefined = active. Independent
   *  of `status`: an archived deal can still be open/won/lost. */
  archived_at?: string | null;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
  /**
   * Client-derived, not a DB column — the color of the "last internal
   * responder" indicator bar, merged in by `loadDeals` (pipelines page)
   * from the same source `colorForConversation` uses for the Inbox, so
   * a lead's card matches in both places. Undefined until that merge
   * runs.
   */
  responder_color?: ResponderColor;
}

/**
 * 'ready' and 'cancelled' added in migration 075 for Campaigns:
 * 'ready' = audience + template picked, recipients materialized, not
 * sent yet (produced by "review recipients" before send); 'cancelled'
 * = a draft/ready campaign the user decided not to run. 'scheduled'
 * is kept for wire compatibility though nothing schedules a send yet.
 */
export type BroadcastStatus =
  | 'draft'
  | 'ready'
  | 'scheduled'
  | 'sending'
  | 'sent'
  | 'failed'
  | 'cancelled';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

/**
 * 'api' (default) sends via the official WhatsApp Business API using
 * an approved template — the flow built in migration 075. 'external'
 * sends a free-text message (+ optional image) manually through an
 * already-authenticated WhatsApp Web session — WACRM only prepares
 * and registers the campaign/recipients; it never calls Meta for
 * these rows. Migration 076.
 */
export type SendChannel = 'api' | 'external';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  /** Optional planning note — migration 075 (Campaigns). */
  description?: string | null;
  /** migration 076 — 'api' (default) or 'external' (WhatsApp Web). */
  send_channel: SendChannel;
  /** NULL for send_channel = 'external' (migration 076). */
  template_name: string | null;
  template_language: string;
  template_variables?: Record<string, unknown>;
  /** Free-text body for send_channel = 'external' — migration 076. When message_variants is set, this holds variant A (index 0) for backward compatibility. */
  message_text?: string | null;
  /** A/B/C+ message variants for send_channel = 'external' (migration 081) — 2+ entries means recipients rotate through them round-robin in send order; NULL/single entry = message_text alone is used, unchanged. */
  message_variants?: string[] | null;
  audience_filter?: Record<string, unknown>;
  /** Media header URL (API) or the optional external-message image (migration 076). */
  header_media_url?: string | null;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Set once the user approves the previewed/edited 'external'
   * recipient list — migration 077. Locks further edits/removals;
   * "Exportar para Claude Code" only appears once this is set.
   */
  approved_at?: string | null;
  /** Last time the export file was generated — migration 077, informational only. */
  exported_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * 'external' campaigns only (migration 077) — the final, approved
   * per-recipient message. NULL = use the computed default
   * (campaign.message_text with {{nome}} substituted); non-NULL = the
   * user's manual per-recipient edit.
   */
  message_text?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Envios — WhatsApp pessoal via Baileys embutido (migration 078)
// ============================================================

export type EnvioStatus = 'rascunho' | 'em_andamento' | 'concluido';
export type EnvioLoteStatus = 'aguardando' | 'em_andamento' | 'pausado' | 'concluido';
export type EnvioLeadStatus = 'na_fila' | 'enviando' | 'enviado' | 'falhou';
export type BaileysStatusConexao = 'desconectado' | 'pareando' | 'conectado';

export interface Envio {
  id: string;
  account_id: string;
  /** Optional, purely informational link to an existing Campaign. */
  campanha_id: string | null;
  nome: string;
  status: EnvioStatus;
  canal: 'baileys';
  /** Shared image for every lead (`creative.url` from the uploaded campaign file). */
  mensagem_imagem_url: string | null;
  /** A/B/C+ message variant texts from the upload's `messages` field (migration 080) — `null` for a legacy per-recipient-message envio. */
  variantes_mensagem: string[] | null;
  created_by: string | null;
  created_at: string;
}

export interface EnvioLote {
  id: string;
  envio_id: string;
  /** 1-based, sequential; up to MAX_LOTES (src/lib/envios/lote-engine.ts) — no longer fixed at 1 or 2 (migration 080). */
  numero_lote: number;
  quantidade_leads: number;
  status: EnvioLoteStatus;
  iniciado_em: string | null;
  concluido_em: string | null;
}

export interface EnvioLead {
  id: string;
  lote_id: string;
  nome: string | null;
  telefone: string;
  /** Final text for this lead — either `recipients[i].message` (legacy) or the rotated variant from `envios.variantes_mensagem` (migration 080). */
  mensagem: string;
  /** 0-based index into `envios.variantes_mensagem` this lead was assigned, or `null` for a legacy per-recipient-message envio (migration 080). */
  variante_indice: number | null;
  status: EnvioLeadStatus;
  /** When the cron tick (GET /api/envios/cron) should next attempt this lead. */
  next_attempt_at: string | null;
  enviado_em: string | null;
  erro: string | null;
  created_at: string;
}

/** Client-facing subset of `baileys_sessao` — never the encrypted creds column. */
export interface BaileysSessao {
  id: string;
  account_id: string;
  identificador: string;
  status_conexao: BaileysStatusConexao;
  updated_at: string;
  created_at: string;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply'
  /** A human agent's first outbound (sender_type='agent') message in a
   *  conversation — fires once per conversation, never for automation/
   *  bot sends (those persist as sender_type='bot') and never again
   *  once the agent has sent a prior message there. */
  | 'first_agent_message';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}
