import { NextResponse } from 'next/server'
import { requireRole, toErrorResponse } from '@/lib/auth/account'
import type { FollowupPlan } from '@/lib/ai/followup-types'

function bad(message: string, status = 400) {
  return NextResponse.json({ error: message }, { status })
}

function addDays(date: Date, days: number): Date {
  const result = new Date(date)
  result.setDate(result.getDate() + days)
  return result
}

/**
 * POST /api/ai/suggestions/[id]/followup/complete  (agent+)
 *
 * "Follow-up realizado" — the manual confirmation for the "Copiar
 * para WhatsApp" mode (the CRM has no visibility into a send made
 * from the agent's personal WhatsApp, so this is the only way that
 * mode ever resolves) and a fallback for "Enviar pelo CRM" in case the
 * automatic resolve-on-send (see /api/whatsapp/send) didn't fire.
 * Idempotent: completing an already-done follow-up is a no-op success,
 * not an error — a double click must not throw.
 *
 * `mode: 'plan'` (Follow-up Inteligente) instead approves a 2-contact
 * plan generated by .../followup/generate: persists it to
 * `followup_plans` and queues its sends into `scheduled_sends`, which
 * the existing follow-up cron (processDueFollowupSends) dispatches on
 * schedule via the same `engineSendTemplate` the automations engine
 * already uses — no new send path.
 */
export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params
    const { supabase, accountId, userId } = await requireRole('agent')

    const body = await request.json().catch(() => null)
    const mode = body?.mode
    if (mode !== 'whatsapp' && mode !== 'crm' && mode !== 'plan') {
      return bad('mode must be "whatsapp", "crm" or "plan"')
    }
    const message = typeof body?.message === 'string' ? body.message : null
    const templateId = typeof body?.template_id === 'string' ? body.template_id : null
    const planData = mode === 'plan' ? (body?.planData as FollowupPlan | undefined) : undefined

    const { data: existing, error: fetchError } = await supabase
      .from('ai_suggestions')
      .select('id, category, status, payload, contact_id, conversation_id')
      .eq('id', id)
      .eq('account_id', accountId)
      .maybeSingle()
    if (fetchError) return bad('Failed to load suggestion', 500)
    if (!existing) return bad('Not found', 404)
    if (existing.category !== 'followup') return bad('Suggestion is not a follow-up')
    if (existing.status === 'done') {
      return NextResponse.json({ success: true, already_done: true })
    }

    if (mode === 'plan') {
      if (!planData || (!planData.contact1 && !planData.contact2)) {
        return bad('planData with at least one contact is required')
      }
      if (!existing.contact_id || !existing.conversation_id) {
        return bad('Suggestion has no contact/conversation to schedule for')
      }

      const { data: plan, error: planError } = await supabase
        .from('followup_plans')
        .insert({
          account_id: accountId,
          contact_id: existing.contact_id,
          conversation_id: existing.conversation_id,
          plan_data: planData,
          status: 'active',
        })
        .select('id')
        .single()
      if (planError || !plan) {
        console.error('[followup complete] plan insert error:', planError)
        return bad('Failed to save followup plan', 500)
      }

      const now = new Date()
      const sendsToCreate: Array<Record<string, unknown>> = []
      let contact1SendAt = now

      if (planData.contact1 && planData.contact1.scheduleDays > 0) {
        contact1SendAt = addDays(now, planData.contact1.scheduleDays)
        sendsToCreate.push({
          account_id: accountId,
          contact_id: existing.contact_id,
          followup_plan_id: plan.id,
          send_at: contact1SendAt.toISOString(),
          template_name: planData.contact1.template_name,
          template_language: planData.contact1.template_language,
          template_params: { values: planData.contact1.values },
        })
      }

      if (planData.contact2 && planData.contact2.scheduleDays > 0) {
        const contact2SendAt = addDays(contact1SendAt, planData.contact2.scheduleDays)
        sendsToCreate.push({
          account_id: accountId,
          contact_id: existing.contact_id,
          followup_plan_id: plan.id,
          send_at: contact2SendAt.toISOString(),
          template_name: planData.contact2.template_name,
          template_language: planData.contact2.template_language,
          template_params: { values: planData.contact2.values },
        })
      }

      if (sendsToCreate.length > 0) {
        const { error: sendsError } = await supabase.from('scheduled_sends').insert(sendsToCreate)
        if (sendsError) {
          console.error('[followup complete] scheduled sends insert error:', sendsError)
          // The plan row exists but has no sends — leave it 'active'
          // rather than silently losing it; an operator can retry via
          // "Regenerar" + approve again, which creates a fresh plan.
          return bad('Failed to schedule followup sends', 500)
        }
      }
    }

    const payload = (existing.payload ?? {}) as Record<string, unknown>
    const { error } = await supabase
      .from('ai_suggestions')
      .update({
        status: 'done',
        resolved_by: userId,
        resolved_at: new Date().toISOString(),
        snoozed_until: null,
        payload: {
          ...payload,
          realized_mode: mode,
          realized_message: message,
          realized_template_id: templateId,
          realized_at: new Date().toISOString(),
        },
      })
      .eq('id', id)
      .eq('account_id', accountId)

    if (error) {
      console.error('[followup complete] update error:', error)
      return bad('Failed to record the follow-up', 500)
    }

    return NextResponse.json({ success: true })
  } catch (err) {
    return toErrorResponse(err)
  }
}
